In [34]:
import numpy as np
import pandas as pd
import matplotlib.pyplot
import scipy.linalg as lg

In [194]:
n = 3
m = 2
alpha = 1e-1

In [190]:
x_ = np.arange(n).reshape((n, 1))
y_ = np.array([1, 2]).reshape((m, 1))
y_

array([[1],
       [2]])

In [191]:
y_

array([[1],
       [2]])

In [203]:
%%time
XTX = np.eye(n)
XTy = np.zeros((n, m))

XTX1 = lg.inv(XTX)

for i in range(100):
    #1
    x = x_ * np.sqrt(alpha)
    y = y_ * np.sqrt(alpha)
    
    XTX1 /= (1 - alpha)
    
    XT_XTX = x.T @ XTX1
    scalar = np.sqrt(1.0 + (XT_XTX @ x)[0, 0])
    XT_XTX /= scalar
    XTX1 -= XT_XTX.T @ XT_XTX
    
#     XTX1 -= (XTX1 @ x) @ (x.T @ XTX1) / (1 + (x.T @ XTX1 @ x)[0, 0])

#     print(XTX1)
    
    XTy *= (1 - alpha)
    XTy += x @ y.T

    print(XTX1)
    print(XTy)
    print(x_.T @ XTX1 @ XTy)
    print()
    
    #2
#     x = x_
#     y = y_
    
#     XTX -= XTX @ x @ x.T @ XTX / (1 + (x.T @ XTX @ x)[0, 0])
#     XTy += x @ y.T

    #3
#     x = x_ * np.sqrt(alpha)
#     y = y_
    
#     XTX *= (1 - alpha)
#     XTX += x @ x.T
    
# #     print(lg.inv(XTX))
    
# #     print()
    
#     XTy *= (1 - alpha)
#     XTy += x @ y.T

[[ 1.11111111  0.         -0.        ]
 [ 0.          1.03174603 -0.15873016]
 [ 0.         -0.15873016  0.79365079]]
[[0.  0. ]
 [0.1 0.2]
 [0.2 0.4]]
[[0.35714286 0.71428571]]

[[ 1.2345679   0.         -0.        ]
 [ 0.          1.10129068 -0.26655443]
 [ 0.         -0.26655443  0.70145903]]
[[0.   0.  ]
 [0.19 0.38]
 [0.38 0.76]]
[[0.53977273 1.07954545]]

[[ 1.37174211  0.         -0.        ]
 [ 0.          1.19336298 -0.35675827]
 [ 0.         -0.35675827  0.65822558]]
[[0.    0.   ]
 [0.271 0.542]
 [0.542 1.084]]
[[0.65019194 1.30038388]]

[[ 1.5241579   0.         -0.        ]
 [ 0.          1.30351558 -0.44128465]
 [ 0.         -0.44128465  0.64158861]]
[[0.     0.    ]
 [0.3439 0.6878]
 [0.6878 1.3756]]
[[0.72381714 1.44763428]]

[[ 1.69350878  0.         -0.        ]
 [ 0.          1.43062089 -0.52577579]
 [ 0.         -0.52577579  0.6419572 ]]
[[0.      0.     ]
 [0.40951 0.81902]
 [0.81902 1.63804]]
[[0.77616336 1.55232673]]

[[ 1.88167642  0.         -0.        ]
 [ 0. 

In [147]:
x.T @ lg.inv(XTX) @ XTy

array([[250500., 501000.]])

In [199]:
x.T @ XTX1 @ XTy

array([[0.99999469, 1.99998938]])

In [130]:
XTX = np.eye(n) * 100

In [131]:
XTX + x_ @ x_.T

array([[100.,   0.,   0.],
       [  0., 101.,   2.],
       [  0.,   2., 104.]])

In [132]:
XTX1 = lg.inv(XTX)
XTX1 -= XTX1 @ x_ @ x_.T @ XTX1 / (1 + (x_.T @ XTX1 @ x_)[0, 0])
lg.inv(XTX1)

array([[100.,  -0.,  -0.],
       [  0., 101.,   2.],
       [  0.,   2., 104.]])